---
- name: Web Admin Setup
  # ansible-playbook site.yml --extra-vars "remote_host=$(user)@$(address)"
  hosts: {{ remote_host }}
  remote_user: centos
  become: yes
  roles:
    - common
    - selinux
    - ps-web-admin
    - certs  