#cloud-config
packages: 
  - vim
runcmd: 
  - yum install -y vim
  - yum install -y epel-release
  - yum install -y http://software.internet2.edu/rpms/el7/x86_64/main/RPMS/perfSONAR-repo-0.8-1.noarch.rpm
  - yum clean all
  #Disable Security-Enhanced
  - bash /root/disableSEL.sh
  - timedatectl set-timezone America/New_York
  - bash /root/installNormal.sh #Local ou Normal
  - /usr/lib/perfsonar/scripts/configure_firewall install
  - bash /root/setupToolkit.sh
write_files:
  - content: |
      #!/bin/bash
      mkdir /mnt/data
      mount /dev/vdb1 /media/data
      rpm -i /media/data/perfsonar-toolkit/*.rpm
    path: /root/installLocal.sh
  - content: |
      #!/bin/bash
      yum install -y perfsonar-toolkit
    path: /root/installNormal.sh
  - content: |
      #!/bin/bash
      echo 0 > /sys/fs/selinux/enforce
      sed -i 's/^SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
    path: /root/disableSEL.sh
  - content: |
      #!/bin/bash
      echo -e pavillen | htpasswd -i /etc/perfsonar/toolkit/psadmin.htpasswd pavillen
      #psconfig remote add "url des instruction de PWA ie https://url/pub/config" ?????
    path: /root/setupToolkit.sh
output: { all: "| tee -a /var/log/output-cloud-init.log" }
