---
- name: Perfsonar toolkit and setup
  hosts: centos@206.12.91.158
  remote_user: centos
  become: yes
  roles:
    - common
    - selinux
    - ps-toolkit
    - certs

  tasks: 
    - debug:
        msg: "Login as root to finish the setup!"   