---
- name: Perfsonar toolkit Setup
  hosts: pstoolkit
  remote_user: pavillen
  become: yes
  roles:
    - common
    - selinux
    - ps-toolkit
    - certs

  tasks: 
    - debug:
        msg: "Login as root to finish the setup!"   
