---
- name: Installing Docker
  yum:
    name: docker
    state: latest


- name: Fetching PWA scripts
  command: wget https://github.com/perfsonar/psconfig-web/raw/master/deploy/docker/pwa.sample.tar.gz


- name: Extracting to correct directories
  command: tar -C /etc -xvf pwa.sample.tar.gz pwa && sudo tar -C /usr/local/sbin --strip-components=1 -xvf pwa.sample.tar.gz scripts


- name: Configuring PWA to run on port 8000 & 8443
  command: {{ commands }}
  with_items:
  #PWA must run on a different port than MadDash ie. 8000 and 8443
  - sed -i 's#listen       80;#listen       8000;#g' /etc/pwa/nginx/conf.d/pwa.conf
  - sed -i 's#listen       443 ssl;#listen       8443;#g' /etc/pwa/nginx/conf.d/pwa.conf
  - sed -i 's#-p 80:80#-p 8000:8000#g' /usr/local/sbin/start_pwa_containers.sh
  - sed -i 's#-p 443:443#-p 8443:8443#g' /usr/local/sbin/start_pwa_containers.sh
  #Thanks but no thanks for relative paths...
  - sed -i 's#./start_pwa_containers.sh#/usr/local/sbin/start_pwa_containers.sh#g' /usr/local/sbin/update_pwa_containers.sh


- name: Downloading and starting Docker Containers (Very long...)
  command: /usr/local/sbin/start_pwa_containers.sh

- name: Copying custom scripts to /root/
    copy:
      src: ~/scripts/*
      dest: /root

