---
# Speedtest
- name: Customizing based on the selected flavour
  copy:
    src: "speedtest/computecanada.png"
    dest: "/var/www/speedtest/speedtest-border.png"
  when: organisation_flavour == "1"

- name: Customizing based on the selected flavour
  copy:
    src: "speedtest/calculquebec.png"
    dest: "/var/www/speedtest/speedtest-border.png"
  when: organisation_flavour == "2"

- name: Customizing based on the selected flavour
  copy:
    src: "speedtest/westgrid.png"
    dest: "/var/www/speedtest/speedtest-border.png"
  when: organisation_flavour == "3"

- name: Customizing based on the selected flavour
  copy:
    src: "speedtest/canarie.png"
    dest: "/var/www/speedtest/speedtest-border.png"
  when: organisation_flavour == "4"

- name: Customizing based on the selected flavour
  copy:
    src: "speedtest/risq.png"
    dest: "/var/www/speedtest/speedtest-border.png"
  when: organisation_flavour == "5"


# Perfsonar
- name: Customizing based on the selected flavour
  copy:
    src: "perfsonar/computecanada.png"
    dest: "/usr/lib/perfsonar/web-ng/root/images/perfSONAR-logo-reversed-green.png"
  when: organisation_flavour == "1"

- name: Customizing based on the selected flavour
  copy:
    src: "perfsonar/calculquebec.png"
    dest: "/usr/lib/perfsonar/web-ng/root/images/perfSONAR-logo-reversed-green.png"
  when: organisation_flavour == "2"

- name: Customizing based on the selected flavour
  copy:
    src: "perfsonar/westgrid.png"
    dest: "/usr/lib/perfsonar/web-ng/root/images/perfSONAR-logo-reversed-green.png"
  when: organisation_flavour == "3"

- name: Customizing based on the selected flavour
  copy:
    src: "perfsonar/canarie.png"
    dest: "/usr/lib/perfsonar/web-ng/root/images/perfSONAR-logo-reversed-green.png"
  when: organisation_flavour == "4"

- name: Customizing based on the selected flavour
  copy:
    src: "perfsonar/risq.png"
    dest: "/usr/lib/perfsonar/web-ng/root/images/perfSONAR-logo-reversed-green.png"
  when: organisation_flavour == "5"

- name: Restarting Apache
  service:
    name: httpd
    state: restarted
  when: organisation_flavour != "0"
  