---
- name: Download and extracting speedtest files
  unarchive:
    src: "speedtest.tar.xz"
    dest: "/var/www/"

- name: Installing prerequisite packages
  yum:
    name: php
    state: latest

- name: Adding speedtest to apache config
  copy:
    src: "speedtest.conf"
    dest: "/etc/httpd/conf.d/speedtest.conf"
    mode: 0644

- name: Generating download test file
  command: dd if=/dev/urandom of=/var/www/speedtest/1gb bs=1048576 count=1024 #1Gb

- name: Transfering index.html
  copy:
    src: "index.html"
    dest: "/var/www/speedtest"
    mode: 0644

- name: Restarting Apache
  service:
    name: httpd
    state: restarted