---
- name: Installing Docker
  yum:
    name: docker
    state: latest


- name: Adding config to /etc/docker/daemon.json
  lineinfile:
    path: /etc/docker/daemon.json
    regexp: '^{}'
    line: {"graph": "/usr/local/docker"}


- name: Enabling and starting docker service
  service:
    name: docker
    enabled: yes
    state: started


- name: Extracting pwa files
  unarchive:
    src: https://github.com/perfsonar/psconfig-web/raw/master/deploy/docker/pwa.sample.tar.gz
    dest: /etc
    remote_src: yes
    extra_opts:
    - pwa


- name: Extracting pwa scripts
  unarchive:
    src: https://github.com/perfsonar/psconfig-web/raw/master/deploy/docker/pwa.sample.tar.gz
    dest: /usr/local/sbin/
    remote_src: yes
    extra_opts:
        - --strip-components=1
        - scripts


#- name: Configuring PWA to run on port 8000 & 8443
#  command: {{ commands }}
#  with_items:
  #PWA must run on a different port than MadDash ie. 8000 and 8443
  #- sed -i 's#listen       80;#listen       8000;#g' /etc/pwa/nginx/conf.d/pwa.conf
  #- sed -i 's#listen       443 ssl;#listen       8443;#g' /etc/pwa/nginx/conf.d/pwa.conf
  #- sed -i 's#-p 80:80#-p 8000:8000#g' /usr/local/sbin/start_pwa_containers.sh
  #- sed -i 's#-p 443:443#-p 8443:8443#g' /usr/local/sbin/start_pwa_containers.sh
  #Thanks but no thanks for relative paths...
  #- sed -i 's#./start_pwa_containers.sh#/usr/local/sbin/start_pwa_containers.sh#g' /usr/local/sbin/update_pwa_containers.sh

- name: Modifying PWA scripts
  lineinfile:
    path: /usr/local/sbin/update_pwa_containers.sh
    regexp: '^./start_pwa_containers.sh'
    line: /usr/local/sbin/start_pwa_containers.sh


- name: Copying custom scripts to /root/
  copy:
    src: "pwaAddAdmin.sh"
    dest: "/root/pwaAddAdmin.sh"
    mode: 0755


- name: Creating PWAdocker.service
  copy:
    src: "PWAdocker.service"
    dest: "/etc/systemd/system/PWAdocker.service"


# PWA will take longer to restart at boot since it will try update itself
- name: Enabling PWAdocker.service
  systemd:
    daemon_reload: yes
    name: PWAdocker
    enabled: yes


- name: Initializing docker
  command: /usr/local/sbin/init_docker.sh

# Otherwise the container wont even start
- name: Generating self-signed certificate for nginx
  command: /usr/local/sbin/generate_nginx_cert.sh


- name: Downloading and starting Docker Containers (Very long...)
  command: /usr/local/sbin/start_pwa_containers.sh



